name: dio_refresh
description: "A flutter package for intercepting requests and automatically fetching refresh tokens on API failures"
version: 1.0.5
homepage: https://github.com/iamdipanshusingh/dio_refresh
repository: https://github.com/iamdipanshusingh/dio_refresh
topics:
  - dio
  - http
  - network
  - interceptor
  - middleware

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  jwt_decoder: ^2.0.1
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dartdoc: ^8.1.0
